#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    
    countpositive=0;
    countnegative=0;
    countzero=0;
    for i in range(len(arr)):
        if (arr[i] > 0):
            countpositive +=1;
        elif(arr[i] < 0):
            countnegative +=1;
        elif(arr[i] == 0):
            countzero += 1;
    print('%.6f' %(countpositive / len(arr)))
    print('%.6f' %(countnegative / len(arr)))
    print('%.6f' %(countzero / len(arr)))
       
               
       

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
